<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Elementor\V4;

/**
 * Compiles a Stonewright atomic widget spec into PHP source for an Elementor V4
 * `Atomic_Widget_Base` subclass.
 *
 * The compiler is intentionally narrow:
 *   - It emits a single class that extends \Elementor\Modules\AtomicWidgets\Elements\Atomic_Widget_Base.
 *   - `define_atomic_controls()` returns one control per declared prop, each
 *     wrapped in an `Atomic_Prop_Schemas` typed envelope.
 *   - `render()` writes the template verbatim, with `{{ name }}` placeholders
 *     replaced by the matching prop value at runtime via straight str_replace —
 *     no eval, no Twig.
 *
 * Defaults are serialized with var_export so the round-trip is loss-free for
 * all scalar / array prop defaults the V4 atomic schema admits.
 *
 * Spec shape:
 *   [
 *     'slug'     => 'my-card',          // required, [a-z0-9-]+
 *     'title'    => 'My Card',          // optional, defaults to slug
 *     'template' => '<div>{{ heading }}</div>',
 *     'props'    => [                   // optional, may be empty
 *       [ 'name' => 'heading', 'type' => 'string', 'default' => '' ],
 *     ],
 *   ]
 *
 * The class name derives deterministically from the slug:
 *   my-card  → Stonewright_Atomic_My_Card_Widget
 *
 * Schema methods (spec type → Atomic_Prop_Schemas method):
 *   string  → string
 *   number  → number
 *   size    → size
 *   color   → color
 *   boolean → boolean
 *   link    → link
 *   image   → image
 *   (any unknown type falls back to `string` so the compiler never throws on
 *   an unfamiliar prop type; the runtime atomic schema will still reject
 *   anything genuinely incoherent.)
 */
final class AtomicCompiler {

	/**
	 * Spec types we know how to bridge to Atomic_Prop_Schemas methods. Anything
	 * not in this map collapses to the `string` schema in {@see schema_method()}.
	 *
	 * @var array<string, string>
	 */
	private const SCHEMA_METHODS = [
		'string'  => 'string',
		'number'  => 'number',
		'size'    => 'size',
		'color'   => 'color',
		'boolean' => 'boolean',
		'link'    => 'link',
		'image'   => 'image',
	];

	/**
	 * Compile a widget spec into a PHP source string.
	 *
	 * @param array<string, mixed> $spec
	 * @return string Raw PHP source (begins with `<?php`).
	 */
	public static function compile( array $spec ): string {
		$slug     = (string) ( $spec['slug'] ?? '' );
		$title    = (string) ( $spec['title'] ?? $slug );
		$template = (string) ( $spec['template'] ?? '' );
		$props    = (array)  ( $spec['props'] ?? [] );

		$class_name      = self::slug_to_class( $slug );
		$controls_source = self::build_controls_block( $props );
		$render_source   = self::build_render_block( $template, $props );

		$title_literal = var_export( $title, true );
		$slug_literal  = var_export( $slug, true );

		return <<<PHP
<?php
declare( strict_types=1 );

namespace Stonewright\\GeneratedAtomicWidgets;

use Elementor\\Modules\\AtomicWidgets\\Elements\\Atomic_Widget_Base;
use Elementor\\Modules\\AtomicWidgets\\PropTypes\\Atomic_Prop_Schemas;

if ( ! defined( 'ABSPATH' ) ) { exit; }

/**
 * Generated by Stonewright AtomicCompiler. Do not edit by hand.
 * Spec slug: {$slug}
 */
final class {$class_name} extends Atomic_Widget_Base {

\tpublic function get_name(): string {
\t\treturn {$slug_literal};
\t}

\tpublic function get_title(): string {
\t\treturn {$title_literal};
\t}

\tprotected function define_atomic_controls(): array {
\t\treturn [
{$controls_source}
\t\t];
\t}

\tprotected function render(): void {
{$render_source}
\t}
}
PHP;
	}

	/**
	 * Map a kebab-case slug to the PascalCase class name the compiler emits.
	 * Rejects slugs that do not match `[a-z0-9-]+` so a hostile slug cannot
	 * inject namespace separators or PHP keywords into the generated source.
	 */
	public static function slug_to_class( string $slug ): string {
		if ( '' === $slug || ! preg_match( '/^[a-z0-9-]+$/', $slug ) ) {
			throw new \InvalidArgumentException( 'Invalid slug: ' . $slug );
		}

		$parts  = explode( '-', $slug );
		$camel  = array_map(
			static fn( string $part ): string => ucfirst( $part ),
			$parts
		);
		return 'Stonewright_Atomic_' . implode( '_', $camel ) . '_Widget';
	}

	/**
	 * Translate a spec prop type to the Atomic_Prop_Schemas factory method
	 * name. Unknown types fall back to `string`; the runtime schema still
	 * validates the actual value shape.
	 */
	public static function schema_method( string $type ): string {
		return self::SCHEMA_METHODS[ $type ] ?? 'string';
	}

	// -------------------------------------------------------------------------
	// Private builders
	// -------------------------------------------------------------------------

	/**
	 * @param array<int, array<string, mixed>> $props
	 */
	private static function build_controls_block( array $props ): string {
		if ( [] === $props ) {
			return '';
		}

		$lines = [];
		foreach ( $props as $prop ) {
			if ( ! is_array( $prop ) || ! isset( $prop['name'] ) ) {
				continue;
			}
			$name   = (string) $prop['name'];
			$type   = (string) ( $prop['type'] ?? 'string' );
			$method = self::schema_method( $type );

			// We deliberately var_export the default so PHP literals round-trip
			// losslessly. Lambdas / resources are not valid defaults in the spec
			// schema and never reach this point.
			$default_literal = array_key_exists( 'default', $prop )
				? var_export( $prop['default'], true )
				: 'null';
			$name_literal = var_export( $name, true );

			$lines[] = "\t\t\t{$name_literal} => Atomic_Prop_Schemas::{$method}()->default( {$default_literal} ),";
		}

		return implode( "\n", $lines );
	}

	/**
	 * The template is echoed verbatim with `{{ name }}` placeholders replaced
	 * by str_replace at runtime. Note: this is intentionally NOT a parser —
	 * the compiler does not evaluate expressions, just substitutes prop
	 * values. The template string itself is embedded as a single literal so
	 * even an attacker who controls the template cannot influence what PHP is
	 * generated; the worst they can do is craft a noisy HTML string.
	 *
	 * @param array<int, array<string, mixed>> $props
	 */
	private static function build_render_block( string $template, array $props ): string {
		$template_literal = var_export( $template, true );

		$prop_names = [];
		foreach ( $props as $prop ) {
			if ( is_array( $prop ) && isset( $prop['name'] ) ) {
				$prop_names[] = (string) $prop['name'];
			}
		}

		$lines   = [];
		$lines[] = "\t\t\$template = {$template_literal};";
		$lines[] = "\t\t\$settings = \$this->get_atomic_settings();";

		if ( [] === $prop_names ) {
			// No props: echo the template as-is, no substitutions to make.
			$lines[] = "\t\techo \$template;";
			return implode( "\n", $lines );
		}

		// Build search/replace arrays as PHP literals so the generated code
		// runs in O(n) per render without rebuilding the lookup each call.
		$search_parts  = [];
		$replace_parts = [];
		foreach ( $prop_names as $name ) {
			$name_literal     = var_export( $name, true );
			$search_parts[]   = var_export( '{{ ' . $name . ' }}', true );
			$replace_parts[]  = "(string) ( \$settings[{$name_literal}] ?? '' )";
		}

		$lines[] = "\t\t\$search = [ " . implode( ', ', $search_parts ) . ' ];';
		$lines[] = "\t\t\$replace = [ " . implode( ', ', $replace_parts ) . ' ];';
		$lines[] = "\t\techo str_replace( \$search, \$replace, \$template );";

		return implode( "\n", $lines );
	}
}
