<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\QA;

/**
 * Manages per-request artifact directories under wp-content/uploads/stonewright-qa/.
 *
 * PHP generates the request_id (via wp_generate_uuid4()) and reserves the
 * directory. The path is then passed to the companion in the request payload.
 * The companion MUST validate that paths match the allowed pattern before
 * writing — see ARTIFACT_PATH_RE in companion/src/http-api.ts.
 *
 * AGENTS.md constraint: the companion never writes to WordPress. All artifact
 * paths are generated here (PHP side) and passed into companion requests.
 * Companion never invents its own paths.
 */
final class QaArtifactStore {

	/**
	 * Reserve a per-request directory.
	 *
	 * Creates WP_CONTENT_DIR/uploads/stonewright-qa/{request_id}/ and returns
	 * the absolute path. The directory is created with mode 0755 so the web
	 * server can serve files from it.
	 *
	 * @param  string $request_id UUID v4 generated by the caller.
	 * @return string Absolute path to the reserved directory (with trailing slash).
	 */
	public static function reserve( string $request_id ): string {
		$base_dir = WP_CONTENT_DIR . '/uploads/stonewright-qa/' . $request_id;
		wp_mkdir_p( $base_dir );
		return rtrim( $base_dir, '/' ) . '/';
	}

	/**
	 * Return the public URL for a file inside a reserved artifact directory.
	 *
	 * @param string $artifact_path Absolute filesystem path to the file.
	 * @return string|false Public URL, or false if the path is not inside the uploads dir.
	 */
	public static function url_for( string $artifact_path ): string|false {
		$upload_dir = wp_upload_dir();
		$base_dir   = (string) ( $upload_dir['basedir'] ?? '' );
		$base_url   = (string) ( $upload_dir['baseurl'] ?? '' );

		if ( $base_dir === '' || $base_url === '' ) {
			return false;
		}

		if ( ! str_starts_with( $artifact_path, $base_dir ) ) {
			return false;
		}

		$relative = substr( $artifact_path, strlen( $base_dir ) );
		return $base_url . $relative;
	}

	/**
	 * Return the stonewright-qa base directory.
	 *
	 * @return string Absolute path (no trailing slash).
	 */
	public static function base_dir(): string {
		return WP_CONTENT_DIR . '/uploads/stonewright-qa';
	}

	/**
	 * Delete artifact directories older than $seconds seconds.
	 *
	 * Walks the stonewright-qa base directory and removes any sub-directory
	 * whose mtime is older than ( time() - $seconds ). Returns the count of
	 * directories purged.
	 *
	 * The TTL is also filterable via {@see 'stonewright_qa_artifact_ttl_seconds'}
	 * so site operators can shorten or extend it without modifying code.
	 *
	 * @param  int $seconds Age threshold in seconds. Directories older than this
	 *                      value are deleted. Defaults to 7 days.
	 * @return int Number of directories deleted.
	 */
	public static function purge_older_than( int $seconds = 7 * 24 * 3600 ): int {
		$base = self::base_dir();

		if ( ! is_dir( $base ) ) {
			return 0;
		}

		$cutoff = time() - $seconds;
		$purged = 0;

		$entries = scandir( $base );
		if ( false === $entries ) {
			return 0;
		}

		foreach ( $entries as $entry ) {
			if ( '.' === $entry || '..' === $entry ) {
				continue;
			}

			$dir_path = $base . '/' . $entry;

			if ( ! is_dir( $dir_path ) ) {
				continue;
			}

			$mtime = filemtime( $dir_path );
			if ( false === $mtime ) {
				continue;
			}

			if ( $mtime < $cutoff ) {
				self::remove_directory_recursive( $dir_path );
				++$purged;
			}
		}

		return $purged;
	}

	/**
	 * Recursively delete a directory and all its contents.
	 *
	 * @param string $dir Absolute path to the directory to remove.
	 */
	private static function remove_directory_recursive( string $dir ): void {
		if ( ! is_dir( $dir ) ) {
			return;
		}

		$entries = scandir( $dir );
		if ( false === $entries ) {
			return;
		}

		foreach ( $entries as $entry ) {
			if ( '.' === $entry || '..' === $entry ) {
				continue;
			}

			$path = $dir . '/' . $entry;
			if ( is_link( $path ) ) {
				unlink( $path );
				continue;
			}
			if ( is_dir( $path ) ) {
				self::remove_directory_recursive( $path );
			} else {
				unlink( $path );
			}
		}

		rmdir( $dir );
	}

	/**
	 * Hook into WP-Cron for daily artifact pruning.
	 *
	 * Called from plugin boot (PluginRegistration). Schedules the
	 * {@see 'stonewright_qa_artifact_purge'} cron action if it is not already
	 * scheduled. The TTL is resolved at purge time via the
	 * {@see 'stonewright_qa_artifact_ttl_seconds'} filter so it can be changed
	 * without rescheduling.
	 */
	public static function schedule_purge(): void {
		if ( ! wp_next_scheduled( 'stonewright_qa_artifact_purge' ) ) {
			wp_schedule_event( time(), 'daily', 'stonewright_qa_artifact_purge' );
		}

		add_action( 'stonewright_qa_artifact_purge', [ self::class, 'run_scheduled_purge' ] );
	}

	/**
	 * Callback for the {@see 'stonewright_qa_artifact_purge'} cron hook.
	 *
	 * Resolves the TTL through the {@see 'stonewright_qa_artifact_ttl_seconds'}
	 * filter (default 7 days) and delegates to {@see self::purge_older_than()}.
	 */
	public static function run_scheduled_purge(): void {
		/** @var int $ttl */
		$ttl = apply_filters( 'stonewright_qa_artifact_ttl_seconds', 7 * 24 * 3600 );
		self::purge_older_than( (int) $ttl );
	}
}
