/** Generated from plugin/data/clients/*.json. Do not edit by hand. */
export const AUTHORITATIVE_CLIENT_CATALOG = [
	{
		"id": "amazon-q",
		"label": "Amazon Q",
		"supportTier": "community",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": false,
		"appPasswordSupport": true,
		"relistBehavior": "restart-app",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "antigravity",
		"label": "Antigravity",
		"supportTier": "unknown",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": false,
		"appPasswordSupport": true,
		"relistBehavior": "reload-or-restart",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "low-tools"
	},
	{
		"id": "antigravity-cli",
		"label": "Antigravity CLI",
		"supportTier": "unknown",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": true,
		"appPasswordSupport": true,
		"relistBehavior": "restart-session",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "low-tools"
	},
	{
		"id": "chatgpt",
		"label": "ChatGPT",
		"supportTier": "community",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": true,
		"appPasswordSupport": true,
		"relistBehavior": "reload-or-restart",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "claude-ai",
		"label": "Claude.ai",
		"supportTier": "community",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": true,
		"appPasswordSupport": true,
		"relistBehavior": "reload-or-restart",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "claude-code",
		"label": "Claude Code",
		"supportTier": "community",
		"configFormat": "cli-only",
		"officialCliAdd": "claude mcp add",
		"oauthSupport": false,
		"appPasswordSupport": true,
		"relistBehavior": "restart-session",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "claude-desktop",
		"label": "Claude Desktop",
		"supportTier": "compatible",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": false,
		"appPasswordSupport": true,
		"relistBehavior": "restart-app",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "cline",
		"label": "Cline",
		"supportTier": "community",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": false,
		"appPasswordSupport": true,
		"relistBehavior": "reload-window",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "codex",
		"label": "Codex",
		"supportTier": "compatible",
		"configFormat": "toml-codex",
		"officialCliAdd": "codex mcp add",
		"oauthSupport": true,
		"appPasswordSupport": true,
		"relistBehavior": "restart-or-reload-mcp",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "codex-cli",
		"label": "Codex CLI",
		"supportTier": "compatible",
		"configFormat": "toml-codex",
		"officialCliAdd": "codex mcp add",
		"oauthSupport": true,
		"appPasswordSupport": true,
		"relistBehavior": "restart-or-reload-mcp",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "cursor",
		"label": "Cursor",
		"supportTier": "compatible",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": true,
		"appPasswordSupport": true,
		"relistBehavior": "reload-window",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "gemini-cli",
		"label": "Gemini CLI",
		"supportTier": "community",
		"configFormat": "cli-only",
		"officialCliAdd": "gemini mcp add",
		"oauthSupport": false,
		"appPasswordSupport": true,
		"relistBehavior": "restart-session",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "low-tools"
	},
	{
		"id": "generic-mcp",
		"label": "Generic MCP",
		"supportTier": "community",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": false,
		"appPasswordSupport": true,
		"relistBehavior": "client-specific",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential-static"
	},
	{
		"id": "github-copilot",
		"label": "GitHub Copilot",
		"supportTier": "community",
		"configFormat": "json-servers",
		"officialCliAdd": "",
		"oauthSupport": true,
		"appPasswordSupport": true,
		"relistBehavior": "reload-window",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "kilo-code",
		"label": "Kilo Code",
		"supportTier": "unknown",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": false,
		"appPasswordSupport": true,
		"relistBehavior": "reload-window",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "opencode",
		"label": "OpenCode",
		"supportTier": "unknown",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": false,
		"appPasswordSupport": true,
		"relistBehavior": "restart-session",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "roo-code",
		"label": "Roo Code",
		"supportTier": "unknown",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": false,
		"appPasswordSupport": true,
		"relistBehavior": "reload-window",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "vscode-copilot",
		"label": "VS Code (Copilot)",
		"supportTier": "compatible",
		"configFormat": "json-servers",
		"officialCliAdd": "",
		"oauthSupport": true,
		"appPasswordSupport": true,
		"relistBehavior": "reload-window",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "windsurf",
		"label": "Windsurf",
		"supportTier": "community",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": false,
		"appPasswordSupport": true,
		"relistBehavior": "reload-window",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	},
	{
		"id": "zed",
		"label": "Zed",
		"supportTier": "community",
		"configFormat": "json-mcp",
		"officialCliAdd": "",
		"oauthSupport": false,
		"appPasswordSupport": true,
		"relistBehavior": "restart-session",
		"newTaskRequiredAfterCatalogChange": true,
		"safeToolBudget": 40,
		"defaultProfile": "essential"
	}
] as const;
