/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-redundant-type-constituents */
// GENERATED FILE — do not edit manually.
// Regenerate with: npm run build:contracts
//
// Sources: companion/src/contracts/*.schema.json
// Tool: json-schema-to-typescript

export interface Viewport {
  width: number;
  height: number;
}

export interface ScreenshotRequest {
  /**
   * UUID v4 generated by PHP; companion echoes it back in the response.
   */
  request_id: string;
  /**
   * Target URL — must be an absolute http/https URL. Never a file:// or data: URL.
   */
  url: string;
  /**
   * Per-request directory reserved by PHP QaArtifactStore::reserve(). Companion rejects any path not matching this pattern.
   */
  artifact_path: string;
  viewport?: Viewport;
  full_page?: boolean;
  wait_for?: "load" | "domcontentloaded" | "networkidle" | "commit";
  wait_ms?: number;
  /**
   * CSS selector — screenshot only the matched element.
   */
  selector?: string;
}

export interface ScreenshotResponse {
  request_id: string;
  /**
   * Unique identifier for this artifact (filename without extension).
   */
  artifact_id: string;
  /**
   * Absolute filesystem path to the saved PNG inside artifact_path.
   */
  path: string;
  /**
   * Public URL for the screenshot (via WordPress uploads).
   */
  url: string;
  width: number;
  height: number;
  viewport: Viewport;
  /**
   * ISO 8601 timestamp.
   */
  created_at: string;
}

export interface IgnoreRegion {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface MismatchRegion {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface DiffRequest {
  request_id: string;
  /**
   * artifact_id from a prior /screenshot response (reference screenshot).
   */
  reference_artifact_id: string;
  /**
   * artifact_id from a prior /screenshot response (actual/current screenshot).
   */
  actual_artifact_id: string;
  /**
   * Directory where the diff PNG will be written.
   */
  artifact_path: string;
  threshold?: number;
  ignore_regions?: IgnoreRegion[];
}

export interface DiffResponse {
  request_id: string;
  /**
   * True when no reference screenshot exists. When true, diff_ratio/passed/diff_url/mismatch_regions MUST be absent.
   */
  needs_reference: boolean;
  /**
   * Fraction of mismatched pixels. Present only when needs_reference=false.
   */
  diff_ratio?: number;
  /**
   * True when diff_ratio <= threshold. Present only when needs_reference=false.
   */
  passed?: boolean;
  threshold?: number;
  /**
   * Public URL to the diff PNG. Present only when needs_reference=false.
   */
  diff_url?: string;
  /**
   * Bounding boxes of clustered mismatch regions. Present only when needs_reference=false.
   */
  mismatch_regions?: MismatchRegion[];
}

export interface AxeViolation {
  rule: string;
  impact: "minor" | "moderate" | "serious" | "critical";
  help: string;
  nodes: {
    html?: string;
    target?: string[];
    [k: string]: any | undefined;
  }[];
  [k: string]: any | undefined;
}

export interface AxeRequest {
  request_id: string;
  /**
   * Target URL resolved by PHP.
   */
  url: string;
  ruleset?: "wcag2a" | "wcag2aa" | "wcag2aaa" | "wcag21a" | "wcag21aa" | "best-practice";
}

export interface AxeResponse {
  request_id: string;
  violations: AxeViolation[];
  passes_count: number;
  incomplete_count?: number;
}

export interface LayoutSection {
  name: string;
  tag: string;
  selector?: string;
  rect: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
  [k: string]: any | undefined;
}

export interface AlignmentDiff {
  type: "overflow" | "overlap" | "missing" | "extra";
  detail: string;
  element?: string;
  [k: string]: any | undefined;
}

export interface LayoutRequest {
  request_id: string;
  /**
   * Target URL resolved by PHP.
   */
  url: string;
  viewport?: {
    width: number;
    height: number;
  };
}

export interface LayoutResponse {
  request_id: string;
  sections: LayoutSection[];
  alignment_diffs: AlignmentDiff[];
  has_horizontal_overflow: boolean;
  has_element_overlap: boolean;
}

export interface LighthouseScores {
  performance?: number | null;
  accessibility?: number | null;
  "best-practices"?: number | null;
  seo?: number | null;
}

export interface LighthouseRequest {
  request_id: string;
  /**
   * Target URL resolved by PHP.
   */
  url: string;
  /**
   * @minItems 1
   */
  categories?: [
    "performance" | "accessibility" | "best-practices" | "seo" | "pwa",
    ...("performance" | "accessibility" | "best-practices" | "seo" | "pwa")[]
  ];
  /**
   * Directory for the Lighthouse HTML report.
   */
  artifact_path?: string;
}

export interface LighthouseResponse {
  request_id: string;
  /**
   * False when the lighthouse binary is not installed. PHP surfaces 503.
   */
  available: boolean;
  scores?: LighthouseScores;
  /**
   * Public URL to the HTML report. Present only when available=true.
   */
  report_url?: string;
  /**
   * Audit IDs that failed. Present only when available=true.
   */
  audits_failed?: string[];
}

/**
 * GET /health has no request body.
 */

export interface HealthRequest {}

export interface HealthResponse {
  status: "ok";
  /**
   * Semantic version of this contract set. PHP checks major-version compatibility.
   */
  contract_version: string;
}
