<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: Facebook Embed (slug: facebook-embed)
 */
final class AddFacebookEmbed extends WidgetAbilityBase {
	protected function slug(): string {
		return 'facebook-embed';
	}
}
