<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: Facebook Page (slug: facebook-page)
 */
final class AddFacebookPage extends WidgetAbilityBase {
	protected function slug(): string {
		return 'facebook-page';
	}
}
