<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: Google Maps (slug: google_maps)
 */
final class AddGoogleMaps extends WidgetAbilityBase {
	protected function slug(): string {
		return 'google_maps';
	}
}
