<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: Portfolio (slug: portfolio)
 */
final class AddPortfolio extends WidgetAbilityBase {
	protected function slug(): string {
		return 'portfolio';
	}
}
