<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: Star Rating (slug: star-rating)
 */
final class AddStarRating extends WidgetAbilityBase {
	protected function slug(): string {
		return 'star-rating';
	}
}
