<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: Post Excerpt (slug: theme-post-excerpt)
 */
final class AddThemePostExcerpt extends WidgetAbilityBase {
	protected function slug(): string {
		return 'theme-post-excerpt';
	}
}
