<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: Text Editor (slug: text-editor)
 */
final class AddTextEditor extends WidgetAbilityBase {
	protected function slug(): string {
		return 'text-editor';
	}
}
