<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: Product Title (slug: woocommerce-product-title)
 */
final class AddWoocommerceProductTitle extends WidgetAbilityBase {
	protected function slug(): string {
		return 'woocommerce-product-title';
	}
}
