<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: My Account (slug: woocommerce-my-account)
 */
final class AddWoocommerceMyAccount extends WidgetAbilityBase {
	protected function slug(): string {
		return 'woocommerce-my-account';
	}
}
