<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: Archive Description (slug: woocommerce-archive-description)
 */
final class AddWoocommerceArchiveDescription extends WidgetAbilityBase {
	protected function slug(): string {
		return 'woocommerce-archive-description';
	}
}
