<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: Custom Add To Cart (slug: wc-add-to-cart)
 */
final class AddWcAddToCart extends WidgetAbilityBase {
	protected function slug(): string {
		return 'wc-add-to-cart';
	}
}
