<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: Purchase Summary (slug: woocommerce-purchase-summary)
 */
final class AddWoocommercePurchaseSummary extends WidgetAbilityBase {
	protected function slug(): string {
		return 'woocommerce-purchase-summary';
	}
}
