<?php
declare( strict_types=1 );

namespace Stonewright\WpMcp\Abilities\ElementorWidgets;

/**
 * Generated by plugin/bin/generate-widget-abilities.php — do not edit
 * by hand. Re-run the generator after the manifest changes.
 *
 * Widget: Product Stock (slug: woocommerce-product-stock)
 */
final class AddWoocommerceProductStock extends WidgetAbilityBase {
	protected function slug(): string {
		return 'woocommerce-product-stock';
	}
}
