// SPDX-License-Identifier: GPL-2.0-or-later
import type { NestedEditorTool, NestedToolResult } from "../types.js";
import { DeclaredToolSet } from "../editor-tools/declared-tool-set.js";
import { checkSchema, validateArgs } from "../editor-tools/schema-guard.js";
import { canonical, digest, object, WorkspaceFailure } from "../session/protocol.js";
import type { NativeBlockPort, BlockSpec, BlockNode } from "./native-port.js";
const schema = (props: object = {}, required: string[] = []): object => ({ type: "object", additionalProperties: false, properties: props, required });
const mutation = (props: object, required: string[]): object => schema({ ...props, confirm_write: { const: true }, idempotency_key: { type: "string", minLength: 1, maxLength: 128 } }, [...required, "confirm_write", "idempotency_key"]);
const string = { type: "string", minLength: 1, maxLength: 256 }; const attrs = { type: "object" }; const placement = { parent_id: string, index: { type: "integer", minimum: 0 } };
const result = (details: Record<string, unknown>): NestedToolResult => ({ content: [{ type: "text", text: "Native editor operation completed." }], details });
export class NativeBlockTools {
  private readonly replay = new Map<string, { args: string; promise: Promise<NestedToolResult> }>();
  constructor(private readonly port: NativeBlockPort) {}
  registry(): DeclaredToolSet { return new DeclaredToolSet(this.tools(), { begin: async () => { const checkpoint = await this.port.checkpoint(); const keys = new Set(this.replay.keys()); return { commit: async () => {}, rollback: async () => { await this.port.restore(checkpoint); for (const key of this.replay.keys()) if (!keys.has(key)) this.replay.delete(key); } }; } }, { insert_block: { primaryResultField: "client_id", publicResultFields: { client_id: { type: "string" } } } }, () => this.port.tree()); }
  tools(): NestedEditorTool[] {
    const read = (name: string, parameters: object, execute: (args: Record<string, unknown>) => Promise<NestedToolResult>): NestedEditorTool => ({ name, parameters, execute });
    const write = (name: string, parameters: object, execute: (args: Record<string, unknown>) => Promise<NestedToolResult>, verify: (args: Record<string, unknown>, output: NestedToolResult) => Promise<unknown>, batchable = true): NestedEditorTool => ({ name, parameters, mutates: true, batchable, execute: (args) => this.idempotent(name, args, execute), readback: verify });
    return [
      read("list_blocks", schema({ search: { type: "string" }, offset: { type: "integer", minimum: 0 }, limit: { type: "integer", minimum: 1, maximum: 200 } }), async (args) => { const rows = (await this.port.registeredBlocks()).filter((row) => !args.search || row.name.includes(String(args.search))); const offset = Number(args.offset ?? 0), limit = Number(args.limit ?? 50); return result({ blocks: rows.slice(offset, offset + limit), total: rows.length, next_offset: offset + limit < rows.length ? offset + limit : null }); }),
      read("get_block_schema", schema({ name: string }, ["name"]), async (args) => result({ name: args.name, schema: await this.attributeSchema(String(args.name)) })),
      read("get_page_structure", schema(), async () => { const tree = await this.port.tree(); return result({ tree, tree_hash: await digest(tree), session_id: this.port.identity() }); }),
      read("get_block", schema({ client_id: string }, ["client_id"]), async (args) => result({ block: await this.requireBlock(String(args.client_id)) })),
      read("serialize", schema(), async () => result({ html: await this.port.serialize(await this.port.tree()) })),
      write("insert_block", mutation({ name: string, attributes: attrs, innerBlocks: { type: "array", maxItems: 500 }, ...placement }, ["name"]), async (args) => { const spec = await this.checkedSpec({ name: args.name, attributes: args.attributes ?? {}, innerBlocks: args.innerBlocks ?? [] }); const ids = await this.port.insert(spec, args.parent_id as string | undefined, args.index as number | undefined); return result({ client_id: ids[0], client_ids: ids, attributes: spec.attributes }); }, async (args, output) => { const node = await this.requireBlock(String(output.details?.client_id)); if (node.name !== args.name || !this.contains(node.attributes, object(args.attributes ?? {}))) throw new WorkspaceFailure("workspace_readback_failed", "Inserted block does not match."); }),
      write("update_block", mutation({ client_id: string, attributes: attrs }, ["client_id", "attributes"]), async (args) => { const node = await this.requireBlock(String(args.client_id)); validateArgs(checkSchema(await this.attributeSchema(node.name)), args.attributes); await this.port.update(node.clientId, object(args.attributes)); return result({ client_id: node.clientId }); }, async (args) => { if (!this.contains((await this.requireBlock(String(args.client_id))).attributes, object(args.attributes))) throw new WorkspaceFailure("workspace_readback_failed", "Updated attributes do not match."); }),
      write("move_block", mutation({ client_id: string, ...placement }, ["client_id", "index"]), async (args) => { await this.requireBlock(String(args.client_id)); await this.port.move([String(args.client_id)], args.parent_id as string | undefined, args.index as number); return result({ client_id: args.client_id }); }, async (args) => { const siblings = args.parent_id ? (await this.requireBlock(String(args.parent_id))).innerBlocks : await this.port.tree(); if (siblings[Number(args.index)]?.clientId !== args.client_id) throw new WorkspaceFailure("workspace_readback_failed", "Block placement does not match."); }),
      write("delete_block", mutation({ client_id: string, confirm_delete: { const: true } }, ["client_id", "confirm_delete"]), async (args) => { await this.requireBlock(String(args.client_id)); await this.port.remove([String(args.client_id)]); return result({ client_id: args.client_id }); }, async (args) => { if (await this.port.block(String(args.client_id))) throw new WorkspaceFailure("workspace_readback_failed", "Deleted block remains present."); }),
      ...(["undo", "redo"] as const).map((name) => write(name, mutation({}, []), async () => { const before = await digest(await this.port.tree()); await this.port[name](); const after = await digest(await this.port.tree()); if (before === after) throw new WorkspaceFailure("workspace_history_unchanged", "Native history produced no change."); return result({ tree_hash: after }); }, async (_args, output) => { if (await digest(await this.port.tree()) !== output.details?.tree_hash) throw new WorkspaceFailure("workspace_readback_failed", "History readback changed."); }, false)),
      write("save", mutation({}, []), async () => { await this.port.save(); const deadline = Date.now() + 60000; while (await this.port.dirty()) { if (Date.now() >= deadline) throw new WorkspaceFailure("workspace_save_unverified", "Native save did not clear the dirty flag."); await new Promise((resolve) => setTimeout(resolve, 50)); } return result({ dirty: false }); }, async () => { if (await this.port.dirty()) throw new WorkspaceFailure("workspace_save_unverified", "Native editor is still dirty."); }, false),
    ];
  }
  private async requireBlock(id: string): Promise<BlockNode> { const block = await this.port.block(id); if (!block) throw new WorkspaceFailure("workspace_block_missing", "Block is absent from the active editor."); return block; }
  private async attributeSchema(name: string): Promise<object> {
    const block = (await this.port.registeredBlocks()).find((row) => row.name === name); if (!block) throw new WorkspaceFailure("workspace_block_unknown", "Block is not registered in the live editor.");
    const properties: Record<string, object> = {};
    for (const [key, value] of Object.entries(block.attributes)) properties[key] = { ...(value.type ? { type: value.type } : {}), ...(Array.isArray(value.enum) ? { enum: value.enum } : {}) };
    return schema(properties);
  }
  private async checkedSpec(input: unknown, depth = 0, counter = { count: 0 }): Promise<BlockSpec> { if (depth > 32 || ++counter.count > 500) throw new WorkspaceFailure("workspace_block_limit", "Block spec exceeds structural bounds."); const row = object(input); if (Object.keys(row).some((key) => !["name", "attributes", "innerBlocks"].includes(key)) || typeof row.name !== "string" || !Array.isArray(row.innerBlocks)) throw new WorkspaceFailure("workspace_block_invalid", "Invalid native block spec."); const attributes = object(row.attributes ?? {}); validateArgs(checkSchema(await this.attributeSchema(row.name)), attributes); return { name: row.name, attributes, innerBlocks: await Promise.all(row.innerBlocks.map((child) => this.checkedSpec(child, depth + 1, counter))) }; }
  private contains(actual: Record<string, unknown>, expected: Record<string, unknown>): boolean { return Object.entries(expected).every(([key, value]) => Object.hasOwn(actual, key) && canonical(actual[key]) === canonical(value)); }
  private async idempotent(name: string, args: Record<string, unknown>, run: (args: Record<string, unknown>) => Promise<NestedToolResult>): Promise<NestedToolResult> {
    if (args.confirm_write !== true || typeof args.idempotency_key !== "string" || !args.idempotency_key) throw new WorkspaceFailure("workspace_confirmation_required", "Native writes need confirmation and an idempotency key.");
    const key = `${this.port.identity()}:${name}:${args.idempotency_key}`; const text = canonical(args); const cached = this.replay.get(key);
    if (cached) { if (cached.args !== text) throw new WorkspaceFailure("workspace_idempotency_conflict", "Idempotency key arguments changed."); return cached.promise; }
    if (this.replay.size >= 256) throw new WorkspaceFailure("workspace_action_limit", "Native session replay limit reached.");
    const promise = run(JSON.parse(text)); this.replay.set(key, { args: text, promise }); return promise;
  }
}
